// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKxJFIRXNYExoUFFfSekQab8uwW6PjGn0',
    appId: '1:547078088322:web:d5b59448d7e6a7e625369b',
    messagingSenderId: '547078088322',
    projectId: 'voodoo-board',
    authDomain: 'voodoo-board.firebaseapp.com',
    storageBucket: 'voodoo-board.firebasestorage.app',
    measurementId: 'G-Z6C9HV4FTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkZr-ejyczOW8XfDcXfg8NKwW7x8oRQYU',
    appId: '1:547078088322:android:8d85e764e0561aac25369b',
    messagingSenderId: '547078088322',
    projectId: 'voodoo-board',
    storageBucket: 'voodoo-board.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAondiBPZzIZgbWlGr2YNl6_8qekFu7aZA',
    appId: '1:547078088322:ios:544cea9d37c72ddf25369b',
    messagingSenderId: '547078088322',
    projectId: 'voodoo-board',
    storageBucket: 'voodoo-board.firebasestorage.app',
    iosBundleId: 'com.example.voodooboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAondiBPZzIZgbWlGr2YNl6_8qekFu7aZA',
    appId: '1:547078088322:ios:544cea9d37c72ddf25369b',
    messagingSenderId: '547078088322',
    projectId: 'voodoo-board',
    storageBucket: 'voodoo-board.firebasestorage.app',
    iosBundleId: 'com.example.voodooboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKxJFIRXNYExoUFFfSekQab8uwW6PjGn0',
    appId: '1:547078088322:web:b5a80c6ee611166d25369b',
    messagingSenderId: '547078088322',
    projectId: 'voodoo-board',
    authDomain: 'voodoo-board.firebaseapp.com',
    storageBucket: 'voodoo-board.firebasestorage.app',
    measurementId: 'G-JCLNKYZVC2',
  );
}
