// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'app.dart'; // Your root app widget

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  if (kIsWeb) {
    // Handle any pending OAuth redirect result before UI loads
    try {
      final result = await FirebaseAuth.instance.getRedirectResult();
      if (result.user != null) {
        // Optionally, handle the signed-in user info.
        // For example, update some state or log the user in silently.
        print("User signed in: ${result.user?.displayName}");
      }
    } catch (_) {
      // No redirect result or error occurred
      print("No redirect result or error.");
    }
  }

  runApp(const VoodooBoardApp());
}
